version: '3'
services:
  vue:
    build: ./build/vue
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ../:/usr/src/app
    command: npm run build
  flask:
    build: ./build/flask
    volumes:
    - ../server/:/usr/src/app
    command: bash -c "pip install -r requirements.txt && python3 web_server.py"
    ports:
      - 8080:8080